# Generated by Django 4.1.4 on 2022-12-12 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_world_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.PositiveIntegerField(default=datetime.date(2022, 12, 12), verbose_name='Премьера в мире'),
        ),
    ]
